README.rst, docs/guide.rst, docs/index.rst, docs/mlp.rst, sknn/mlp.py, sknn/tests/test_classifier.py, sknn/tests/test_conv.py, sknn/tests/test_deep.py, sknn/tests/test_layers.py, sknn/tests/test_linear.py, sknn/tests/test_output.py, sknn/tests/test_pipeline.py, sknn/tests/test_rules.py, sknn/tests/test_sklearn.py, sknn/tests/test_training.py, sknn/tests/test_types.py
=> More powerful features for layer specification: convolution, activation types, nested parameters.

sknn/mlp.py, sknn/tests/test_classifier.py, sknn/tests/test_conv.py
=> Improvements to convolution support: repr, border_mode and kernel_stride.

.gitignore, sknn/dataset.py, sknn/mlp.py, sknn/tests/test_types.py
This doesn't work with convolution, but that's probably OK?
=> Support for sparse matrices as input to fit()

README.rst, examples/plot_mlp.py, sknn/mlp.py, sknn/pywrap2.py, sknn/tests/test_classifier.py, sknn/tests/test_rules.py
=> Regularization support using L1 and L2, not just dropout, includes minor API changes.

sknn/mlp.py, sknn/tests/test_output.py
=> Support for MAE as cost function, with an explicit parameter loss_type.

docs/pypi.rst, sknn/mlp.py, sknn/pywrap2.py, sknn/tests/test_training.py
=> Explicit Error Notice when NaN is detected by RuntimeError

README.rst, docs/guide_advanced.rst, docs/guide_beginners.rst, docs/guide_installation.rst, docs/guide_intermediate.rst, docs/index.rst, examples/bench_cifar10.py, sknn/ae.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_ae.py
This acts as a form of unsupervised layer-wise pretraining.
=> Support to transfer weights from autoencoder to mlp

docs/guide_intermediate.rst, examples/bench_cifar10.py, examples/bench_mnist.py, sknn/nn.py, sknn/tests/test_training.py
=> Automatically configuring logger if it has not been setup

examples/plot_digits.py, examples/plot_mlp.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_conv.py, sknn/tests/test_linear.py
New `plot_digits.py` example, using convolution.
Closes #60.
=> Converting input array shapes internally when they don't match

sknn/ae.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_classifier.py, sknn/tests/test_training.py, sknn/tests/test_types.py
=> Various fixes to input parameter processing

sknn/mlp.py, sknn/nn.py, sknn/tests/test_linear.py
Also minor fixes to formatting, logging.
Closes #78. Updates #71.
=> Allowing training after serialisation, not forcing predictions to 32 bits.

examples/plot_mlp.py, sknn/ae.py, sknn/backend/pylearn2/ae.py, sknn/backend/pylearn2/mlp.py, sknn/backend/pylearn2/nn.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_conv.py, sknn/tests/test_linear.py, sknn/tests/test_nn.py, sknn/tests/test_rules.py, sknn/tests/test_sklearn.py
=> Refactoring of the back-end support using pimpl pattern.

sknn/backend/pylearn2/dataset.py, sknn/tests/test_types.py
=> Support for mixed input types: sparse matrices and dense arrays.

docs/guide_beginners.rst, examples/bench_mnist.py, sknn/mlp.py, sknn/tests/test_classifier.py
=> Transparent multi-label support for Classifier

docs/conf.py, examples/bench_mnist.py, sknn/__init__.py, sknn/ae.py, sknn/backend/__init__.py, sknn/backend/pylearn2/pywrap2.py, sknn/mlp.py, sknn/nn.py
=> Improved backend support and documentation.

sknn/backend/pylearn2/dataset.py, sknn/backend/pylearn2/nn.py, sknn/nn.py, sknn/tests/test_data.py, sknn/tests/test_types.py
=> Support for dataset augmentation as a mutator called for each sample/epoch.

sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_callback.py, sknn/tests/test_data.py, sknn/tests/test_training.py, sknn/tests/test_types.py
Training, Epoch and Batch observers.
=> Callback Implementation

sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_conv.py, sknn/tests/test_data.py, sknn/tests/test_rules.py
Support for output convolution layer, and some transposing if axis don't match. An image must be specified as Y in this case.
=> Output Layer Convolution

sknn/backend/lasagne/mlp.py, sknn/nn.py, sknn/tests/test_conv.py, sknn/tests/test_data.py, sknn/tests/test_deep.py
=> Exponential Linear Units

docs/guide_intermediate.rst, sknn/__init__.py, sknn/tests/test_platform.py
=> Helpers to set the number of threads when running on OpenMP via the CPU.

examples/bench_mnist.py, sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/tests/test_classifier.py, sknn/tests/test_training.py
- Prediction should not return score.
Closes #169.
=> Fixes and improvements of batch iterator

sknn/mlp.py, sknn/tests/test_classifier.py, sknn/tests/test_data.py, sknn/tests/test_sklearn.py
=> Multi-feature classification predict_proba returns a list of arrays.

.travis.yml, sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/tests/test_types.py
=> Support for pandas.DataFrame

.travis.yml, requirements.txt, sknn/backend/base.py, sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_deep.py, sknn/tests/test_rules.py
In the entire network or only certain layers.
=> Support for Batch Normalization

sknn/backend/lasagne/mlp.py, sknn/mlp.py, sknn/nn.py, sknn/tests/test_native.py
Support for Lasagne-specific layers for advanced users.
=> Native Layers
